logging:
  level.: WARN
  level.no.acat: INFO
  level.org.springframework: WARN
  level.org.springframework.web: WARN
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
server:
  port: 8087
management:
  server:
    port: 8997
