logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: DEBUG
  level.org.springframework: DEBUG
  level.org.springframework.web: DEBUG
  level.org.elasticsearch: DEBUG
server:
  port: 8080
management:
  server:
    port: 8181
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  crawlerThreadPoolSize: 2
  elasticSearchHost: elasticsearch
  elasticSearchPort: 9300
  elasticSearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}
  themesHostname: http://reference-data:8080
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin

---
spring:
  profiles: prod
  mail:
    host: smtprelay.brreg.no
application:
  elasticSearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}
  notificationMailSenderAddress: ${emailSenderAddress}

---
spring:
  profiles: develop, unit-integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true

fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  crawlerThreadPoolSize: 2
  elasticSearchHost: localhost
  elasticSearchPort: 9300
  elasticSearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}
  themesHostname: http://localhost:8100
  notificationMailSenderAddress: fdksystembjg@gmail.com
server:
  port: 8081
management:
  server:
    port: 8991

---
spring:
  profiles: docker
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
application:
  notificationMailSenderAddress: fdksystembjg@gmail.com