logging:
  level.: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
  fusekiService: http://fuseki:8080/fuseki
server:
  port: 8080
management:
  server:
    port: 8181

---
spring:
  profiles: prod
application:
  elasticsearchHost: ${FDK_ES_HOSTNAME:elasticsearch}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  elasticsearchHost: localhost
  elasticsearchPort: 9300
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
  fusekiService: http://localhost:3030/fuseki
logging:
  level.: ERROR
  level.no.brreg: INFO
  level.org.springframework: ERROR
server:
  port: 8083
management:
  server:
    port: 8993
