logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
server:
  port: 8080
management:
  server:
    port: 8181
application:
  elasticsearchHost: elasticsearch
  elasticsearchPort: 9300
  elasticsearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}
  fusekiHost: http://fuseki:8080
  harvesterHost: http://harvester-api:8080

---
spring:
  profiles: prod
application:
  elasticsearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop
application:
  elasticsearchHost: localhost
  elasticsearchPort: 9300
  elasticsearchCluster: ${FDK_ES_CLUSTERNAME:elasticsearch}
  fusekiHost: http://localhost:3030
  harvesterHost: http://localhost:8081
server:
  port: 8074
management:
  server:
    port: 8994